.include "macro.inc"

.section .sdata

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching D_00001AE8

dlabel D_00001AE8
    /* 001AE8 00001AE8 00000020 */ .word 0x00000020
enddlabel D_00001AE8
