.include "macro.inc"

.section .rodata

.align 4

/* Generated by spimdisasm 1.42.0 */

.align 2
nonmatching RO_STR_00001D58

/* static variable */
dlabel RO_STR_00001D58
    /* 001D58 00001D58 */ .asciz "Gr2SchedMgrSwapBuf: WID %d already swapping buffers\n"
    /* 47723253636865644D6772537761704275663A2057494420256420616C7265616479207377617070696E6720627566666572730A00000000 */
.align 2
enddlabel RO_STR_00001D58

.align 2
nonmatching RO_STR_00001D90

/* static variable */
dlabel RO_STR_00001D90
    /* 001D90 00001D90 */ .asciz "Gr2SchedSwapBuf: WID %d already swapping buffers\n"
    /* 4772325363686564537761704275663A2057494420256420616C7265616479207377617070696E6720627566666572730A000000 */
.align 2
.align 2
    /* 001DC4 00001DC4 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel RO_STR_00001D90

nonmatching RO_00001DC8

/* static variable */
dlabel RO_00001DC8
    /* 001DC8 00001DC8 53657448 */ .word 0x53657448
    /* 001DCC 00001DCC 6F747370 */ .word 0x6F747370
    /* 001DD0 00001DD0 6F743A20 */ .word 0x6F743A20
    /* 001DD4 00001DD4 57524F4E */ .word 0x57524F4E
    /* 001DD8 00001DD8 4720636F */ .word 0x4720636F
    /* 001DDC 00001DDC 6E646974 */ .word 0x6E646974
    /* 001DE0 00001DE0 696F6E73 */ .word 0x696F6E73
enddlabel RO_00001DC8
