.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching Gr2TpHQUcodeSetup, 0x50

glabel Gr2TpHQUcodeSetup # 0
    /* 0005D4 000005D4 3C030000 */  lui         $v1, (0x0 >> 16)
    /* 0005D8 000005D8 24630000 */  addiu       $v1, $v1, %lo(ge_ucode_str)
    /* 0005DC 000005DC 3C010000 */  lui         $at, (0x0 >> 16)
    /* 0005E0 000005E0 24210000 */  addiu       $at, $at, %lo(RO_STR_00003978)
    /* 0005E4 000005E4 8C270018 */  lw          $a3, 0x18($at)
    /* 0005E8 000005E8 246223D0 */  addiu       $v0, $v1, 0x23D0
    /* 0005EC 000005EC 8C260014 */  lw          $a2, 0x14($at)
    /* 0005F0 000005F0 AC672404 */  sw          $a3, 0x2404($v1)
    /* 0005F4 000005F4 8C250010 */  lw          $a1, 0x10($at)
    /* 0005F8 000005F8 AC662400 */  sw          $a2, 0x2400($v1)
    /* 0005FC 000005FC 8C24000C */  lw          $a0, 0xC($at)
    /* 000600 00000600 AC6523FC */  sw          $a1, 0x23FC($v1)
    /* 000604 00000604 8C250008 */  lw          $a1, 0x8($at)
    /* 000608 00000608 AC6423F8 */  sw          $a0, 0x23F8($v1)
    /* 00060C 0000060C 8C240004 */  lw          $a0, 0x4($at)
    /* 000610 00000610 8C210000 */  lw          $at, 0x0($at)
    /* 000614 00000614 AC6523F4 */  sw          $a1, 0x23F4($v1)
    /* 000618 00000618 AC6423F0 */  sw          $a0, 0x23F0($v1)
    /* 00061C 0000061C 03E00008 */  jr          $ra
    /* 000620 00000620 AC6123EC */   sw         $at, 0x23EC($v1)
endlabel Gr2TpHQUcodeSetup

nonmatching Gr2TpGEUcodeSetup, 0x4C

glabel Gr2TpGEUcodeSetup # 1
    /* 000624 00000624 3C020000 */  lui         $v0, (0x0 >> 16)
    /* 000628 00000628 3C010000 */  lui         $at, 0x0
    /* 00062C 0000062C 24210020 */  addiu       $at, $at, %lo(RO_STR_00003998)
    /* 000630 00000630 8C260018 */  lw          $a2, 0x18($at)
    /* 000634 00000634 24420000 */  addiu       $v0, $v0, %lo(ge_ucode_str)
    /* 000638 00000638 8C250014 */  lw          $a1, 0x14($at)
    /* 00063C 0000063C AC460034 */  sw          $a2, 0x34($v0)
    /* 000640 00000640 8C240010 */  lw          $a0, 0x10($at)
    /* 000644 00000644 AC450030 */  sw          $a1, 0x30($v0)
    /* 000648 00000648 8C23000C */  lw          $v1, 0xC($at)
    /* 00064C 0000064C AC44002C */  sw          $a0, 0x2C($v0)
    /* 000650 00000650 8C240008 */  lw          $a0, 0x8($at)
    /* 000654 00000654 AC430028 */  sw          $v1, 0x28($v0)
    /* 000658 00000658 8C230004 */  lw          $v1, 0x4($at)
    /* 00065C 0000065C 8C210000 */  lw          $at, 0x0($at)
    /* 000660 00000660 AC440024 */  sw          $a0, 0x24($v0)
    /* 000664 00000664 AC430020 */  sw          $v1, 0x20($v0)
    /* 000668 00000668 03E00008 */  jr          $ra
    /* 00066C 0000066C AC41001C */   sw         $at, 0x1C($v0)
endlabel Gr2TpGEUcodeSetup

nonmatching Gr2TpSetup, 0x144

glabel Gr2TpSetup # 2
    /* 000670 00000670 27BDFFA0 */  addiu       $sp, $sp, -0x60
    /* 000674 00000674 FFB00008 */  sd          $s0, 0x8($sp)
    /* 000678 00000678 00808025 */  move        $s0, $a0
    /* 00067C 0000067C FFA50020 */  sd          $a1, 0x20($sp)
    /* 000680 00000680 FFA60010 */  sd          $a2, 0x10($sp)
    /* 000684 00000684 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 000688 00000688 0C000000 */  jal         Gr2TpHQUcodeSetup
    /* 00068C 0000068C FFA70018 */   sd         $a3, 0x18($sp)
    /* 000690 00000690 00402825 */  move        $a1, $v0
    /* 000694 00000694 02002025 */  move        $a0, $s0
    /* 000698 00000698 FFB20028 */  sd          $s2, 0x28($sp)
    /* 00069C 0000069C 0C000000 */  jal         Gr2DownloadHQ2
    /* 0006A0 000006A0 00003025 */   move       $a2, $zero
    /* 0006A4 000006A4 DFBF0000 */  ld          $ra, 0x0($sp)
    /* 0006A8 000006A8 3C120002 */  lui         $s2, 0x2
    /* 0006AC 000006AC 10400035 */  beqz        $v0, .L00000784
    /* 0006B0 000006B0 02129021 */   addu       $s2, $s0, $s2
    /* 0006B4 000006B4 0C000000 */  jal         Gr2TpGEUcodeSetup
    /* 0006B8 000006B8 00000000 */   nop
    /* 0006BC 000006BC 00402825 */  move        $a1, $v0
    /* 0006C0 000006C0 02002025 */  move        $a0, $s0
    /* 0006C4 000006C4 0C000000 */  jal         Gr2DownloadGE7
    /* 0006C8 000006C8 00003025 */   move       $a2, $zero
    /* 0006CC 000006CC 10400035 */  beqz        $v0, .L000007A4
    /* 0006D0 000006D0 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0006D4 000006D4 FFB10030 */  sd          $s1, 0x30($sp)
    /* 0006D8 000006D8 3C110004 */  lui         $s1, 0x4
    /* 0006DC 000006DC 02118821 */  addu        $s1, $s0, $s1
    /* 0006E0 000006E0 3C020007 */  lui         $v0, 0x7
    /* 0006E4 000006E4 02021021 */  addu        $v0, $s0, $v0
    /* 0006E8 000006E8 AC40A070 */  sw          $zero, -0x5F90($v0)
    /* 0006EC 000006EC AC40A078 */  sw          $zero, -0x5F88($v0)
    /* 0006F0 000006F0 9042C000 */  lbu         $v0, -0x4000($v0)
    /* 0006F4 000006F4 3C030000 */  lui         $v1, 0x0
    /* 0006F8 000006F8 24630040 */  addiu       $v1, $v1, %lo(jpt_000039B8)
    /* 0006FC 000006FC 00401027 */  not         $v0, $v0
    /* 000700 00000700 3042000F */  andi        $v0, $v0, 0xF
    /* 000704 00000704 2C41000C */  sltiu       $at, $v0, 0xC
    /* 000708 00000708 00021080 */  sll         $v0, $v0, 2
    /* 00070C 0000070C 10200004 */  beqz        $at, .L00000720
    /* 000710 00000710 00431021 */   addu       $v0, $v0, $v1
    /* 000714 00000714 8C430000 */  lw          $v1, 0x0($v0)
    /* 000718 00000718 00600008 */  jr          $v1
    /* 00071C 0000071C 24010001 */   addiu      $at, $zero, 0x1
  jlabel .L00000720
    /* 000720 00000720 24080002 */  addiu       $a4, $zero, 0x2
    /* 000724 00000724 AE280644 */  sw          $a4, (0x40644 & 0xFFFF)($s1)
  .L00000728:
    /* 000728 00000728 0C000000 */  jal         flushbus
    /* 00072C 0000072C 00000000 */   nop
    /* 000730 00000730 0C000000 */  jal         us_delay
    /* 000734 00000734 24040009 */   addiu      $a0, $zero, 0x9
    /* 000738 00000738 02002025 */  move        $a0, $s0
    /* 00073C 0000073C DFA50018 */  ld          $a1, 0x18($sp)
    /* 000740 00000740 DFA90010 */  ld          $a5, 0x10($sp)
    /* 000744 00000744 DFAA0020 */  ld          $a6, 0x20($sp)
    /* 000748 00000748 AE200648 */  sw          $zero, (0x40648 & 0xFFFF)($s1)
    /* 00074C 0000074C AE200654 */  sw          $zero, (0x40654 & 0xFFFF)($s1)
    /* 000750 00000750 AE20077C */  sw          $zero, (0x4077C & 0xFFFF)($s1)
    /* 000754 00000754 AE2A077C */  sw          $a6, (0x4077C & 0xFFFF)($s1)
    /* 000758 00000758 0C000000 */  jal         Gr2BlankScreen
    /* 00075C 0000075C AE29077C */   sw         $a5, (0x4077C & 0xFFFF)($s1)
    /* 000760 00000760 00001025 */  move        $v0, $zero
    /* 000764 00000764 DFB10030 */  ld          $s1, 0x30($sp)
    /* 000768 00000768 DFBF0000 */  ld          $ra, 0x0($sp)
    /* 00076C 0000076C 24100001 */  addiu       $s0, $zero, 0x1
    /* 000770 00000770 AE50FFFC */  sw          $s0, -0x4($s2)
    /* 000774 00000774 DFB00008 */  ld          $s0, 0x8($sp)
  .L00000778:
    /* 000778 00000778 DFB20028 */  ld          $s2, 0x28($sp)
    /* 00077C 0000077C 03E00008 */  jr          $ra
    /* 000780 00000780 27BD0060 */   addiu      $sp, $sp, 0x60
  .L00000784:
    /* 000784 00000784 2402FFFF */  addiu       $v0, $zero, -0x1
    /* 000788 00000788 AE40FFFC */  sw          $zero, -0x4($s2)
    /* 00078C 0000078C 1000FFFA */  b           .L00000778
    /* 000790 00000790 DFB00008 */   ld         $s0, 0x8($sp)
  jlabel .L00000794
    /* 000794 00000794 1000FFE4 */  b           .L00000728
    /* 000798 00000798 AE200644 */   sw         $zero, 0x644($s1)
  jlabel .L0000079C
    /* 00079C 0000079C 1000FFE2 */  b           .L00000728
    /* 0007A0 000007A0 AE210644 */   sw         $at, 0x644($s1)
  .L000007A4:
    /* 0007A4 000007A4 2402FFFF */  addiu       $v0, $zero, -0x1
    /* 0007A8 000007A8 AE40FFFC */  sw          $zero, -0x4($s2)
    /* 0007AC 000007AC 1000FFF2 */  b           .L00000778
    /* 0007B0 000007B0 DFB00008 */   ld         $s0, 0x8($sp)
endlabel Gr2TpSetup
