.include "macro.inc"

.section .rodata

.align 4

/* Generated by spimdisasm 1.42.0 */

.align 2
nonmatching RO_STR_00003978

/* static variable */
dlabel RO_STR_00003978
    /* 003978 00003978 */ .asciz "IP12/GR2 PROM HQ Microcode\n"
    /* 495031322F4752322050524F4D204851204D6963726F636F64650A00 */
.align 2
.align 2
    /* 003994 00003994 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel RO_STR_00003978

.align 2
nonmatching RO_STR_00003998

/* static variable */
dlabel RO_STR_00003998
    /* 003998 00003998 */ .asciz "IP12/GR2 PROM GE Microcode\n"
    /* 495031322F4752322050524F4D204745204D6963726F636F64650A00 */
.align 2
.align 2
    /* 0039B4 000039B4 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel RO_STR_00003998

nonmatching jpt_000039B8

/* static variable */
dlabel jpt_000039B8
    /* 0039B8 000039B8 000001C0 */ .word .L00000794
    /* 0039BC 000039BC 000001C0 */ .word .L00000794
    /* 0039C0 000039C0 000001C0 */ .word .L00000794
    /* 0039C4 000039C4 000001C0 */ .word .L00000794
    /* 0039C8 000039C8 000001C8 */ .word .L0000079C
    /* 0039CC 000039CC 0000014C */ .word .L00000720
    /* 0039D0 000039D0 0000014C */ .word .L00000720
    /* 0039D4 000039D4 0000014C */ .word .L00000720
    /* 0039D8 000039D8 0000014C */ .word .L00000720
    /* 0039DC 000039DC 000001C8 */ .word .L0000079C
    /* 0039E0 000039E0 000001C8 */ .word .L0000079C
    /* 0039E4 000039E4 000001C8 */ .word .L0000079C
enddlabel jpt_000039B8
