.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching dcb_fifowait, 0x58

glabel dcb_fifowait, local # 0
    /* 000834 00000834 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 000838 00000838 FFBF0010 */  sd          $ra, 0x10($sp)
    /* 00083C 0000083C FFB50008 */  sd          $s5, 0x8($sp)
    /* 000840 00000840 0000A825 */  move        $s5, $zero
    /* 000844 00000844 FFB70000 */  sd          $s7, 0x0($sp)
    /* 000848 00000848 3C170007 */  lui         $s7, 0x7
    /* 00084C 0000084C 8F818800 */  lw          $at, %gp_rel(.sbss)($gp)
  .L00000850:
    /* 000850 00000850 02E10821 */  addu        $at, $s7, $at
    /* 000854 00000854 9021C11C */  lbu         $at, -0x3EE4($at)
    /* 000858 00000858 30210001 */  andi        $at, $at, 0x1
    /* 00085C 0000085C 10200006 */  beqz        $at, .L00000878
    /* 000860 00000860 26B50001 */   addiu      $s5, $s5, 0x1
    /* 000864 00000864 0C000000 */  jal         us_delay
    /* 000868 00000868 24040001 */   addiu      $a0, $zero, 0x1
    /* 00086C 0000086C 2AA203E8 */  slti        $v0, $s5, 0x3E8
    /* 000870 00000870 1440FFF7 */  bnez        $v0, .L00000850
    /* 000874 00000874 8F818800 */   lw         $at, %gp_rel(.sbss)($gp)
  .L00000878:
    /* 000878 00000878 DFBF0010 */  ld          $ra, 0x10($sp)
    /* 00087C 0000087C DFB50008 */  ld          $s5, 0x8($sp)
    /* 000880 00000880 DFB70000 */  ld          $s7, 0x0($sp)
    /* 000884 00000884 03E00008 */  jr          $ra
    /* 000888 00000888 27BD0020 */   addiu      $sp, $sp, 0x20
endlabel dcb_fifowait

nonmatching gr2_i2cRead, 0x60

glabel gr2_i2cRead, local # 1
    /* 00088C 0000088C 27BDFFD0 */  addiu       $sp, $sp, -0x30
    /* 000890 00000890 FFA50010 */  sd          $a1, 0x10($sp)
    /* 000894 00000894 FFBE0008 */  sd          $fp, 0x8($sp)
    /* 000898 00000898 0080F025 */  move        $fp, $a0
    /* 00089C 0000089C FFBF0000 */  sd          $ra, 0x0($sp)
    /* 0008A0 000008A0 0C000000 */  jal         us_delay
    /* 0008A4 000008A4 24040001 */   addiu      $a0, $zero, 0x1
    /* 0008A8 000008A8 DFBF0000 */  ld          $ra, 0x0($sp)
    /* 0008AC 000008AC 3C060007 */  lui         $a2, 0x7
    /* 0008B0 000008B0 8F848800 */  lw          $a0, %gp_rel(.sbss)($gp)
    /* 0008B4 000008B4 24010001 */  addiu       $at, $zero, 0x1
    /* 0008B8 000008B8 13C10007 */  beq         $fp, $at, .L000008D8
    /* 0008BC 000008BC 00862021 */   addu       $a0, $a0, $a2
    /* 0008C0 000008C0 DFA10010 */  ld          $at, 0x10($sp)
    /* 0008C4 000008C4 909EC1C0 */  lbu         $fp, -0x3E40($a0)
    /* 0008C8 000008C8 AC3E0000 */  sw          $fp, 0x0($at)
    /* 0008CC 000008CC DFBE0008 */  ld          $fp, 0x8($sp)
  .L000008D0:
    /* 0008D0 000008D0 03E00008 */  jr          $ra
    /* 0008D4 000008D4 27BD0030 */   addiu      $sp, $sp, 0x30
  .L000008D8:
    /* 0008D8 000008D8 DFA30010 */  ld          $v1, 0x10($sp)
    /* 0008DC 000008DC 9082C1C4 */  lbu         $v0, -0x3E3C($a0)
    /* 0008E0 000008E0 DFBE0008 */  ld          $fp, 0x8($sp)
    /* 0008E4 000008E4 1000FFFA */  b           .L000008D0
    /* 0008E8 000008E8 AC620000 */   sw         $v0, 0x0($v1)
endlabel gr2_i2cRead

nonmatching gr2_i2cWrite, 0x58

glabel gr2_i2cWrite, local # 2
    /* 0008EC 000008EC 27BDFFD0 */  addiu       $sp, $sp, -0x30
    /* 0008F0 000008F0 FFA50010 */  sd          $a1, 0x10($sp)
    /* 0008F4 000008F4 FFBE0008 */  sd          $fp, 0x8($sp)
    /* 0008F8 000008F8 0080F025 */  move        $fp, $a0
    /* 0008FC 000008FC FFBF0000 */  sd          $ra, 0x0($sp)
    /* 000900 00000900 0C000000 */  jal         us_delay
    /* 000904 00000904 24040001 */   addiu      $a0, $zero, 0x1
    /* 000908 00000908 DFBF0000 */  ld          $ra, 0x0($sp)
    /* 00090C 0000090C 3C060007 */  lui         $a2, 0x7
    /* 000910 00000910 8F848800 */  lw          $a0, %gp_rel(.sbss)($gp)
    /* 000914 00000914 24010001 */  addiu       $at, $zero, 0x1
    /* 000918 00000918 13C10006 */  beq         $fp, $at, .L00000934
    /* 00091C 0000091C 00862021 */   addu       $a0, $a0, $a2
    /* 000920 00000920 DFBE0010 */  ld          $fp, 0x10($sp)
    /* 000924 00000924 A09EC1C0 */  sb          $fp, -0x3E40($a0)
    /* 000928 00000928 DFBE0008 */  ld          $fp, 0x8($sp)
  .L0000092C:
    /* 00092C 0000092C 03E00008 */  jr          $ra
    /* 000930 00000930 27BD0030 */   addiu      $sp, $sp, 0x30
  .L00000934:
    /* 000934 00000934 DFA10010 */  ld          $at, 0x10($sp)
    /* 000938 00000938 DFBE0008 */  ld          $fp, 0x8($sp)
    /* 00093C 0000093C 1000FFFB */  b           .L0000092C
    /* 000940 00000940 A081C1C4 */   sb         $at, -0x3E3C($a0)
endlabel gr2_i2cWrite

nonmatching gr2_i2cProbe, 0xCC

glabel gr2_i2cProbe # 3
    /* 000944 00000944 AF848800 */  sw          $a0, %gp_rel(.sbss)($gp)
    /* 000948 00000948 27BDFFD0 */  addiu       $sp, $sp, -0x30
    /* 00094C 0000094C FFBF0008 */  sd          $ra, 0x8($sp)
    /* 000950 00000950 FFB30010 */  sd          $s3, 0x10($sp)
    /* 000954 00000954 3C130007 */  lui         $s3, 0x7
    /* 000958 00000958 02640821 */  addu        $at, $s3, $a0
    /* 00095C 0000095C 24040001 */  addiu       $a0, $zero, 0x1
    /* 000960 00000960 0C000000 */  jal         us_delay
    /* 000964 00000964 A020C1E0 */   sb         $zero, -0x3E20($at)
    /* 000968 00000968 8F838800 */  lw          $v1, %gp_rel(.sbss)($gp)
    /* 00096C 0000096C 24040001 */  addiu       $a0, $zero, 0x1
    /* 000970 00000970 24020055 */  addiu       $v0, $zero, 0x55
    /* 000974 00000974 02631821 */  addu        $v1, $s3, $v1
    /* 000978 00000978 0C000000 */  jal         us_delay
    /* 00097C 0000097C A062C1E0 */   sb         $v0, -0x3E20($v1)
    /* 000980 00000980 8F848800 */  lw          $a0, %gp_rel(.sbss)($gp)
    /* 000984 00000984 AFA00000 */  sw          $zero, 0x0($sp)
    /* 000988 00000988 02642021 */  addu        $a0, $s3, $a0
    /* 00098C 0000098C 9080C1E0 */  lbu         $zero, -0x3E20($a0)
    /* 000990 00000990 0C000000 */  jal         us_delay
    /* 000994 00000994 24040001 */   addiu      $a0, $zero, 0x1
    /* 000998 00000998 8F828800 */  lw          $v0, %gp_rel(.sbss)($gp)
    /* 00099C 0000099C 02621021 */  addu        $v0, $s3, $v0
    /* 0009A0 000009A0 9045C1E0 */  lbu         $a1, -0x3E20($v0)
    /* 0009A4 000009A4 24010055 */  addiu       $at, $zero, 0x55
    /* 0009A8 000009A8 10A10006 */  beq         $a1, $at, .L000009C4
    /* 0009AC 000009AC DFBF0008 */   ld         $ra, 0x8($sp)
  .L000009B0:
    /* 0009B0 000009B0 AF808800 */  sw          $zero, %gp_rel(.sbss)($gp)
    /* 0009B4 000009B4 00001025 */  move        $v0, $zero
    /* 0009B8 000009B8 DFB30010 */  ld          $s3, 0x10($sp)
  .L000009BC:
    /* 0009BC 000009BC 03E00008 */  jr          $ra
    /* 0009C0 000009C0 27BD0030 */   addiu      $sp, $sp, 0x30
  .L000009C4:
    /* 0009C4 000009C4 24040001 */  addiu       $a0, $zero, 0x1
    /* 0009C8 000009C8 240300AA */  addiu       $v1, $zero, 0xAA
    /* 0009CC 000009CC A043C1E0 */  sb          $v1, -0x3E20($v0)
    /* 0009D0 000009D0 0C000000 */  jal         us_delay
    /* 0009D4 000009D4 AFA00000 */   sw         $zero, 0x0($sp)
    /* 0009D8 000009D8 8F848800 */  lw          $a0, %gp_rel(.sbss)($gp)
    /* 0009DC 000009DC 02642021 */  addu        $a0, $s3, $a0
    /* 0009E0 000009E0 9080C1E0 */  lbu         $zero, -0x3E20($a0)
    /* 0009E4 000009E4 0C000000 */  jal         us_delay
    /* 0009E8 000009E8 24040001 */   addiu      $a0, $zero, 0x1
    /* 0009EC 000009EC 8F858800 */  lw          $a1, %gp_rel(.sbss)($gp)
    /* 0009F0 000009F0 02652821 */  addu        $a1, $s3, $a1
    /* 0009F4 000009F4 90A5C1E0 */  lbu         $a1, -0x3E20($a1)
    /* 0009F8 000009F8 DFBF0008 */  ld          $ra, 0x8($sp)
    /* 0009FC 000009FC 240100AA */  addiu       $at, $zero, 0xAA
    /* 000A00 00000A00 14A1FFEB */  bne         $a1, $at, .L000009B0
    /* 000A04 00000A04 DFB30010 */   ld         $s3, 0x10($sp)
    /* 000A08 00000A08 1000FFEC */  b           .L000009BC
    /* 000A0C 00000A0C 24020001 */   addiu      $v0, $zero, 0x1
endlabel gr2_i2cProbe

nonmatching gr2_i2cSetup, 0x54

glabel gr2_i2cSetup # 4
    /* 000A10 00000A10 24040001 */  addiu       $a0, $zero, 0x1
    /* 000A14 00000A14 27BDFFF0 */  addiu       $sp, $sp, -0x10
    /* 000A18 00000A18 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 000A1C 00000A1C 0C000000 */  jal         gr2_i2cWrite
    /* 000A20 00000A20 00002825 */   move       $a1, $zero
    /* 000A24 00000A24 00002025 */  move        $a0, $zero
    /* 000A28 00000A28 0C000000 */  jal         gr2_i2cWrite
    /* 000A2C 00000A2C 2405007F */   addiu      $a1, $zero, 0x7F
    /* 000A30 00000A30 24050020 */  addiu       $a1, $zero, 0x20
    /* 000A34 00000A34 0C000000 */  jal         gr2_i2cWrite
    /* 000A38 00000A38 24040001 */   addiu      $a0, $zero, 0x1
    /* 000A3C 00000A3C 00002025 */  move        $a0, $zero
    /* 000A40 00000A40 0C000000 */  jal         gr2_i2cWrite
    /* 000A44 00000A44 2405001C */   addiu      $a1, $zero, 0x1C
    /* 000A48 00000A48 24050040 */  addiu       $a1, $zero, 0x40
    /* 000A4C 00000A4C 0C000000 */  jal         gr2_i2cWrite
    /* 000A50 00000A50 24040001 */   addiu      $a0, $zero, 0x1
    /* 000A54 00000A54 DFBF0000 */  ld          $ra, 0x0($sp)
    /* 000A58 00000A58 24020001 */  addiu       $v0, $zero, 0x1
    /* 000A5C 00000A5C 03E00008 */  jr          $ra
    /* 000A60 00000A60 27BD0010 */   addiu      $sp, $sp, 0x10
endlabel gr2_i2cSetup

nonmatching gr2_i2cStart, 0xE4

glabel gr2_i2cStart, local # 5
    /* 000A64 00000A64 24050040 */  addiu       $a1, $zero, 0x40
    /* 000A68 00000A68 27BDFFD0 */  addiu       $sp, $sp, -0x30
    /* 000A6C 00000A6C FFA40008 */  sd          $a0, 0x8($sp)
    /* 000A70 00000A70 FFBF0010 */  sd          $ra, 0x10($sp)
    /* 000A74 00000A74 0C000000 */  jal         gr2_i2cWrite
    /* 000A78 00000A78 24040001 */   addiu      $a0, $zero, 0x1
    /* 000A7C 00000A7C 27A50000 */  addiu       $a1, $sp, 0x0
    /* 000A80 00000A80 0C000000 */  jal         gr2_i2cRead
    /* 000A84 00000A84 24040001 */   addiu      $a0, $zero, 0x1
    /* 000A88 00000A88 8FA10000 */  lw          $at, 0x0($sp)
    /* 000A8C 00000A8C 24030081 */  addiu       $v1, $zero, 0x81
    /* 000A90 00000A90 10230007 */  beq         $at, $v1, .L00000AB0
    /* 000A94 00000A94 00002025 */   move       $a0, $zero
    /* 000A98 00000A98 0C000000 */  jal         gr2_i2cStop
    /* 000A9C 00000A9C 00000000 */   nop
    /* 000AA0 00000AA0 00001025 */  move        $v0, $zero
  .L00000AA4:
    /* 000AA4 00000AA4 DFBF0010 */  ld          $ra, 0x10($sp)
    /* 000AA8 00000AA8 03E00008 */  jr          $ra
    /* 000AAC 00000AAC 27BD0030 */   addiu      $sp, $sp, 0x30
  .L00000AB0:
    /* 000AB0 00000AB0 0C000000 */  jal         gr2_i2cWrite
    /* 000AB4 00000AB4 DFA50008 */   ld         $a1, 0x8($sp)
    /* 000AB8 00000AB8 FFB40018 */  sd          $s4, 0x18($sp)
    /* 000ABC 00000ABC 24050044 */  addiu       $a1, $zero, 0x44
    /* 000AC0 00000AC0 0C000000 */  jal         gr2_i2cWrite
    /* 000AC4 00000AC4 24040001 */   addiu      $a0, $zero, 0x1
    /* 000AC8 00000AC8 24140064 */  addiu       $s4, $zero, 0x64
    /* 000ACC 00000ACC 27A50000 */  addiu       $a1, $sp, 0x0
  .L00000AD0:
    /* 000AD0 00000AD0 0C000000 */  jal         gr2_i2cRead
    /* 000AD4 00000AD4 24040001 */   addiu      $a0, $zero, 0x1
    /* 000AD8 00000AD8 8FA20000 */  lw          $v0, 0x0($sp)
    /* 000ADC 00000ADC 30460080 */  andi        $a2, $v0, 0x80
    /* 000AE0 00000AE0 10C00009 */  beqz        $a2, .L00000B08
    /* 000AE4 00000AE4 00000000 */   nop
    /* 000AE8 00000AE8 2694FFFF */  addiu       $s4, $s4, -0x1
    /* 000AEC 00000AEC 1680FFF8 */  bnez        $s4, .L00000AD0
    /* 000AF0 00000AF0 27A50000 */   addiu      $a1, $sp, 0x0
  .L00000AF4:
    /* 000AF4 00000AF4 0C000000 */  jal         gr2_i2cStop
    /* 000AF8 00000AF8 00000000 */   nop
    /* 000AFC 00000AFC 00001025 */  move        $v0, $zero
    /* 000B00 00000B00 1000FFE8 */  b           .L00000AA4
    /* 000B04 00000B04 DFB40018 */   ld         $s4, 0x18($sp)
  .L00000B08:
    /* 000B08 00000B08 1280FFFA */  beqz        $s4, .L00000AF4
    /* 000B0C 00000B0C DFA10008 */   ld         $at, 0x8($sp)
    /* 000B10 00000B10 30470008 */  andi        $a3, $v0, 0x8
    /* 000B14 00000B14 10E00005 */  beqz        $a3, .L00000B2C
    /* 000B18 00000B18 DFB40018 */   ld         $s4, 0x18($sp)
    /* 000B1C 00000B1C 0C000000 */  jal         gr2_i2cStop
    /* 000B20 00000B20 00000000 */   nop
    /* 000B24 00000B24 1000FFDF */  b           .L00000AA4
    /* 000B28 00000B28 00001025 */   move       $v0, $zero
  .L00000B2C:
    /* 000B2C 00000B2C 30210001 */  andi        $at, $at, 0x1
    /* 000B30 00000B30 10200003 */  beqz        $at, .L00000B40
    /* 000B34 00000B34 00002025 */   move       $a0, $zero
    /* 000B38 00000B38 0C000000 */  jal         gr2_i2cRead
    /* 000B3C 00000B3C 27A50000 */   addiu      $a1, $sp, 0x0
  .L00000B40:
    /* 000B40 00000B40 1000FFD8 */  b           .L00000AA4
    /* 000B44 00000B44 24020001 */   addiu      $v0, $zero, 0x1
endlabel gr2_i2cStart

nonmatching gr2_i2cReceive, 0x90

glabel gr2_i2cReceive, local # 6
    /* 000B48 00000B48 27BDFFD0 */  addiu       $sp, $sp, -0x30
    /* 000B4C 00000B4C FFBF0018 */  sd          $ra, 0x18($sp)
    /* 000B50 00000B50 FFA40008 */  sd          $a0, 0x8($sp)
    /* 000B54 00000B54 FFB30010 */  sd          $s3, 0x10($sp)
    /* 000B58 00000B58 24130064 */  addiu       $s3, $zero, 0x64
    /* 000B5C 00000B5C 27A50000 */  addiu       $a1, $sp, 0x0
  .L00000B60:
    /* 000B60 00000B60 0C000000 */  jal         gr2_i2cRead
    /* 000B64 00000B64 24040001 */   addiu      $a0, $zero, 0x1
    /* 000B68 00000B68 8FA20000 */  lw          $v0, 0x0($sp)
    /* 000B6C 00000B6C 30410080 */  andi        $at, $v0, 0x80
    /* 000B70 00000B70 1020000B */  beqz        $at, .L00000BA0
    /* 000B74 00000B74 00000000 */   nop
    /* 000B78 00000B78 2673FFFF */  addiu       $s3, $s3, -0x1
    /* 000B7C 00000B7C 1660FFF8 */  bnez        $s3, .L00000B60
    /* 000B80 00000B80 27A50000 */   addiu      $a1, $sp, 0x0
  .L00000B84:
    /* 000B84 00000B84 0C000000 */  jal         gr2_i2cStop
    /* 000B88 00000B88 00000000 */   nop
    /* 000B8C 00000B8C 00001025 */  move        $v0, $zero
    /* 000B90 00000B90 DFBF0018 */  ld          $ra, 0x18($sp)
  .L00000B94:
    /* 000B94 00000B94 DFB30010 */  ld          $s3, 0x10($sp)
    /* 000B98 00000B98 03E00008 */  jr          $ra
    /* 000B9C 00000B9C 27BD0030 */   addiu      $sp, $sp, 0x30
  .L00000BA0:
    /* 000BA0 00000BA0 1260FFF8 */  beqz        $s3, .L00000B84
    /* 000BA4 00000BA4 30430037 */   andi       $v1, $v0, 0x37
    /* 000BA8 00000BA8 10600006 */  beqz        $v1, .L00000BC4
    /* 000BAC 00000BAC 00002025 */   move       $a0, $zero
    /* 000BB0 00000BB0 0C000000 */  jal         gr2_i2cStop
    /* 000BB4 00000BB4 00000000 */   nop
    /* 000BB8 00000BB8 00001025 */  move        $v0, $zero
    /* 000BBC 00000BBC 1000FFF5 */  b           .L00000B94
    /* 000BC0 00000BC0 DFBF0018 */   ld         $ra, 0x18($sp)
  .L00000BC4:
    /* 000BC4 00000BC4 0C000000 */  jal         gr2_i2cRead
    /* 000BC8 00000BC8 DFA50008 */   ld         $a1, 0x8($sp)
    /* 000BCC 00000BCC 24020001 */  addiu       $v0, $zero, 0x1
    /* 000BD0 00000BD0 1000FFF0 */  b           .L00000B94
    /* 000BD4 00000BD4 DFBF0018 */   ld         $ra, 0x18($sp)
endlabel gr2_i2cReceive

nonmatching gr2_i2cSend, 0xA4

glabel gr2_i2cSend, local # 7
    /* 000BD8 00000BD8 00802825 */  move        $a1, $a0
    /* 000BDC 00000BDC 00002025 */  move        $a0, $zero
    /* 000BE0 00000BE0 27BDFFD0 */  addiu       $sp, $sp, -0x30
    /* 000BE4 00000BE4 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 000BE8 00000BE8 0C000000 */  jal         gr2_i2cWrite
    /* 000BEC 00000BEC FFB70010 */   sd         $s7, 0x10($sp)
    /* 000BF0 00000BF0 24170064 */  addiu       $s7, $zero, 0x64
    /* 000BF4 00000BF4 27A50000 */  addiu       $a1, $sp, 0x0
  .L00000BF8:
    /* 000BF8 00000BF8 0C000000 */  jal         gr2_i2cRead
    /* 000BFC 00000BFC 24040001 */   addiu      $a0, $zero, 0x1
    /* 000C00 00000C00 8FA20000 */  lw          $v0, 0x0($sp)
    /* 000C04 00000C04 30410080 */  andi        $at, $v0, 0x80
    /* 000C08 00000C08 1020000B */  beqz        $at, .L00000C38
    /* 000C0C 00000C0C 00000000 */   nop
    /* 000C10 00000C10 26F7FFFF */  addiu       $s7, $s7, -0x1
    /* 000C14 00000C14 16E0FFF8 */  bnez        $s7, .L00000BF8
    /* 000C18 00000C18 27A50000 */   addiu      $a1, $sp, 0x0
  .L00000C1C:
    /* 000C1C 00000C1C 0C000000 */  jal         gr2_i2cStop
    /* 000C20 00000C20 00000000 */   nop
    /* 000C24 00000C24 00001025 */  move        $v0, $zero
    /* 000C28 00000C28 DFB70010 */  ld          $s7, 0x10($sp)
  .L00000C2C:
    /* 000C2C 00000C2C DFBF0008 */  ld          $ra, 0x8($sp)
  .L00000C30:
    /* 000C30 00000C30 03E00008 */  jr          $ra
    /* 000C34 00000C34 27BD0030 */   addiu      $sp, $sp, 0x30
  .L00000C38:
    /* 000C38 00000C38 12E0FFF8 */  beqz        $s7, .L00000C1C
    /* 000C3C 00000C3C 30440008 */   andi       $a0, $v0, 0x8
    /* 000C40 00000C40 30430037 */  andi        $v1, $v0, 0x37
    /* 000C44 00000C44 10600005 */  beqz        $v1, .L00000C5C
    /* 000C48 00000C48 DFB70010 */   ld         $s7, 0x10($sp)
    /* 000C4C 00000C4C 0C000000 */  jal         gr2_i2cStop
    /* 000C50 00000C50 00000000 */   nop
    /* 000C54 00000C54 1000FFF5 */  b           .L00000C2C
    /* 000C58 00000C58 00001025 */   move       $v0, $zero
  .L00000C5C:
    /* 000C5C 00000C5C 10800005 */  beqz        $a0, .L00000C74
    /* 000C60 00000C60 24020001 */   addiu      $v0, $zero, 0x1
    /* 000C64 00000C64 0C000000 */  jal         gr2_i2cStop
    /* 000C68 00000C68 00000000 */   nop
    /* 000C6C 00000C6C 1000FFEF */  b           .L00000C2C
    /* 000C70 00000C70 00001025 */   move       $v0, $zero
  .L00000C74:
    /* 000C74 00000C74 1000FFEE */  b           .L00000C30
    /* 000C78 00000C78 DFBF0008 */   ld         $ra, 0x8($sp)
endlabel gr2_i2cSend

nonmatching gr2_i2cStop, 0x74

glabel gr2_i2cStop, local # 8
    /* 000C7C 00000C7C 240500C2 */  addiu       $a1, $zero, 0xC2
    /* 000C80 00000C80 24040001 */  addiu       $a0, $zero, 0x1
    /* 000C84 00000C84 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 000C88 00000C88 FFB50010 */  sd          $s5, 0x10($sp)
    /* 000C8C 00000C8C FFBF0008 */  sd          $ra, 0x8($sp)
    /* 000C90 00000C90 0C000000 */  jal         gr2_i2cWrite
    /* 000C94 00000C94 FFB70018 */   sd         $s7, 0x18($sp)
    /* 000C98 00000C98 24170081 */  addiu       $s7, $zero, 0x81
    /* 000C9C 00000C9C 2415000A */  addiu       $s5, $zero, 0xA
    /* 000CA0 00000CA0 27A50000 */  addiu       $a1, $sp, 0x0
  .L00000CA4:
    /* 000CA4 00000CA4 0C000000 */  jal         gr2_i2cRead
    /* 000CA8 00000CA8 24040001 */   addiu      $a0, $zero, 0x1
    /* 000CAC 00000CAC 8FA10000 */  lw          $at, 0x0($sp)
    /* 000CB0 00000CB0 1037000A */  beq         $at, $s7, .L00000CDC
    /* 000CB4 00000CB4 00000000 */   nop
    /* 000CB8 00000CB8 26B5FFFF */  addiu       $s5, $s5, -0x1
    /* 000CBC 00000CBC 16A0FFF9 */  bnez        $s5, .L00000CA4
    /* 000CC0 00000CC0 27A50000 */   addiu      $a1, $sp, 0x0
  .L00000CC4:
    /* 000CC4 00000CC4 00001025 */  move        $v0, $zero
    /* 000CC8 00000CC8 DFB50010 */  ld          $s5, 0x10($sp)
    /* 000CCC 00000CCC DFB70018 */  ld          $s7, 0x18($sp)
  .L00000CD0:
    /* 000CD0 00000CD0 DFBF0008 */  ld          $ra, 0x8($sp)
    /* 000CD4 00000CD4 03E00008 */  jr          $ra
    /* 000CD8 00000CD8 27BD0020 */   addiu      $sp, $sp, 0x20
  .L00000CDC:
    /* 000CDC 00000CDC 12A0FFF9 */  beqz        $s5, .L00000CC4
    /* 000CE0 00000CE0 DFB70018 */   ld         $s7, 0x18($sp)
    /* 000CE4 00000CE4 24020001 */  addiu       $v0, $zero, 0x1
    /* 000CE8 00000CE8 1000FFF9 */  b           .L00000CD0
    /* 000CEC 00000CEC DFB50010 */   ld         $s5, 0x10($sp)
endlabel gr2_i2cStop

nonmatching gr2_i2cPortRead, 0x50

glabel gr2_i2cPortRead, local # 9
    /* 000CF0 00000CF0 34840001 */  ori         $a0, $a0, 0x1
    /* 000CF4 00000CF4 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 000CF8 00000CF8 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 000CFC 00000CFC 0C000000 */  jal         gr2_i2cStart
    /* 000D00 00000D00 FFA50008 */   sd         $a1, 0x8($sp)
    /* 000D04 00000D04 1040000B */  beqz        $v0, .L00000D34
    /* 000D08 00000D08 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000D0C 00000D0C 0C000000 */  jal         gr2_i2cReceive
    /* 000D10 00000D10 DFA40008 */   ld         $a0, 0x8($sp)
    /* 000D14 00000D14 10400007 */  beqz        $v0, .L00000D34
    /* 000D18 00000D18 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000D1C 00000D1C 0C000000 */  jal         gr2_i2cStop
    /* 000D20 00000D20 00000000 */   nop
    /* 000D24 00000D24 10400003 */  beqz        $v0, .L00000D34
    /* 000D28 00000D28 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000D2C 00000D2C 10000002 */  b           .L00000D38
    /* 000D30 00000D30 24020001 */   addiu      $v0, $zero, 0x1
  .L00000D34:
    /* 000D34 00000D34 00001025 */  move        $v0, $zero
  .L00000D38:
    /* 000D38 00000D38 03E00008 */  jr          $ra
    /* 000D3C 00000D3C 27BD0020 */   addiu      $sp, $sp, 0x20
endlabel gr2_i2cPortRead

nonmatching gr2_i2cPortWrite, 0x4C

glabel gr2_i2cPortWrite, local # 10
    /* 000D40 00000D40 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 000D44 00000D44 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 000D48 00000D48 0C000000 */  jal         gr2_i2cStart
    /* 000D4C 00000D4C FFA50008 */   sd         $a1, 0x8($sp)
    /* 000D50 00000D50 1040000B */  beqz        $v0, .L00000D80
    /* 000D54 00000D54 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000D58 00000D58 0C000000 */  jal         gr2_i2cSend
    /* 000D5C 00000D5C DFA40008 */   ld         $a0, 0x8($sp)
    /* 000D60 00000D60 10400007 */  beqz        $v0, .L00000D80
    /* 000D64 00000D64 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000D68 00000D68 0C000000 */  jal         gr2_i2cStop
    /* 000D6C 00000D6C 00000000 */   nop
    /* 000D70 00000D70 10400003 */  beqz        $v0, .L00000D80
    /* 000D74 00000D74 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000D78 00000D78 10000002 */  b           .L00000D84
    /* 000D7C 00000D7C 24020001 */   addiu      $v0, $zero, 0x1
  .L00000D80:
    /* 000D80 00000D80 00001025 */  move        $v0, $zero
  .L00000D84:
    /* 000D84 00000D84 03E00008 */  jr          $ra
    /* 000D88 00000D88 27BD0020 */   addiu      $sp, $sp, 0x20
endlabel gr2_i2cPortWrite

nonmatching gr2_i2cPanelID, 0x54

glabel gr2_i2cPanelID # 11
    /* 000D8C 00000D8C 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 000D90 00000D90 FFB00000 */  sd          $s0, 0x0($sp)
    /* 000D94 00000D94 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 000D98 00000D98 0C000000 */  jal         dcb_fifowait
    /* 000D9C 00000D9C 00808025 */   move       $s0, $a0
    /* 000DA0 00000DA0 24040070 */  addiu       $a0, $zero, 0x70
    /* 000DA4 00000DA4 0C000000 */  jal         gr2_i2cPortRead
    /* 000DA8 00000DA8 02002825 */   move       $a1, $s0
    /* 000DAC 00000DAC 10400009 */  beqz        $v0, .L00000DD4
    /* 000DB0 00000DB0 DFBF0008 */   ld         $ra, 0x8($sp)
    /* 000DB4 00000DB4 8E010000 */  lw          $at, 0x0($s0)
    /* 000DB8 00000DB8 24020001 */  addiu       $v0, $zero, 0x1
    /* 000DBC 00000DBC 00010943 */  sra         $at, $at, 5
    /* 000DC0 00000DC0 30210007 */  andi        $at, $at, 0x7
    /* 000DC4 00000DC4 AE010000 */  sw          $at, 0x0($s0)
    /* 000DC8 00000DC8 DFB00000 */  ld          $s0, 0x0($sp)
  .L00000DCC:
    /* 000DCC 00000DCC 03E00008 */  jr          $ra
    /* 000DD0 00000DD0 27BD0020 */   addiu      $sp, $sp, 0x20
  .L00000DD4:
    /* 000DD4 00000DD4 00001025 */  move        $v0, $zero
    /* 000DD8 00000DD8 1000FFFC */  b           .L00000DCC
    /* 000DDC 00000DDC DFB00000 */   ld         $s0, 0x0($sp)
endlabel gr2_i2cPanelID

nonmatching gr2_i2cPanelOn, 0xD0

glabel gr2_i2cPanelOn # 12
    /* 000DE0 00000DE0 AF80881C */  sw          $zero, %gp_rel(.sbss + 0x1C)($gp)
    /* 000DE4 00000DE4 AF808814 */  sw          $zero, %gp_rel(.sbss + 0x14)($gp)
    /* 000DE8 00000DE8 AF808810 */  sw          $zero, %gp_rel(.sbss + 0x10)($gp)
    /* 000DEC 00000DEC AF80880C */  sw          $zero, %gp_rel(.sbss + 0xC)($gp)
    /* 000DF0 00000DF0 AF808808 */  sw          $zero, %gp_rel(.sbss + 0x8)($gp)
    /* 000DF4 00000DF4 AF808804 */  sw          $zero, %gp_rel(.sbss + 0x4)($gp)
    /* 000DF8 00000DF8 27BDFFF0 */  addiu       $sp, $sp, -0x10
    /* 000DFC 00000DFC 24020001 */  addiu       $v0, $zero, 0x1
    /* 000E00 00000E00 AF828818 */  sw          $v0, %gp_rel(.sbss + 0x18)($gp)
    /* 000E04 00000E04 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 000E08 00000E08 3C010000 */  lui         $at, (0x0 >> 16)
    /* 000E0C 00000E0C 24210000 */  addiu       $at, $at, %lo(gr2_i2cPanelOff)
    /* 000E10 00000E10 0C000000 */  jal         dcb_fifowait
    /* 000E14 00000E14 AF810000 */   sw         $at, %gp_rel(fp_poweroff + 0x7800)($gp)
    /* 000E18 00000E18 240500E7 */  addiu       $a1, $zero, 0xE7
    /* 000E1C 00000E1C 0C000000 */  jal         gr2_i2cPortWrite
    /* 000E20 00000E20 24040070 */   addiu      $a0, $zero, 0x70
    /* 000E24 00000E24 1040001F */  beqz        $v0, .L00000EA4
    /* 000E28 00000E28 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E2C 00000E2C 0C000000 */  jal         gr2_i2cAudioVolLeft
    /* 000E30 00000E30 240400F6 */   addiu      $a0, $zero, 0xF6
    /* 000E34 00000E34 1040001B */  beqz        $v0, .L00000EA4
    /* 000E38 00000E38 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E3C 00000E3C 0C000000 */  jal         gr2_i2cAudioVolRight
    /* 000E40 00000E40 240400F6 */   addiu      $a0, $zero, 0xF6
    /* 000E44 00000E44 10400017 */  beqz        $v0, .L00000EA4
    /* 000E48 00000E48 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E4C 00000E4C 0C000000 */  jal         gr2_i2cAudioBass
    /* 000E50 00000E50 240400F6 */   addiu      $a0, $zero, 0xF6
    /* 000E54 00000E54 10400013 */  beqz        $v0, .L00000EA4
    /* 000E58 00000E58 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E5C 00000E5C 0C000000 */  jal         gr2_i2cAudioTreble
    /* 000E60 00000E60 240400F6 */   addiu      $a0, $zero, 0xF6
    /* 000E64 00000E64 1040000F */  beqz        $v0, .L00000EA4
    /* 000E68 00000E68 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E6C 00000E6C 0C000000 */  jal         gr2_i2cAudioSwitch
    /* 000E70 00000E70 240400CE */   addiu      $a0, $zero, 0xCE
    /* 000E74 00000E74 1040000B */  beqz        $v0, .L00000EA4
    /* 000E78 00000E78 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E7C 00000E7C 0C000000 */  jal         gr2_i2cBlUp
    /* 000E80 00000E80 24040064 */   addiu      $a0, $zero, 0x64
    /* 000E84 00000E84 10400007 */  beqz        $v0, .L00000EA4
    /* 000E88 00000E88 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E8C 00000E8C 0C000000 */  jal         gr2_i2cSetBit
    /* 000E90 00000E90 00002025 */   move       $a0, $zero
    /* 000E94 00000E94 10400003 */  beqz        $v0, .L00000EA4
    /* 000E98 00000E98 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 000E9C 00000E9C 10000002 */  b           .L00000EA8
    /* 000EA0 00000EA0 24020001 */   addiu      $v0, $zero, 0x1
  .L00000EA4:
    /* 000EA4 00000EA4 00001025 */  move        $v0, $zero
  .L00000EA8:
    /* 000EA8 00000EA8 03E00008 */  jr          $ra
    /* 000EAC 00000EAC 27BD0010 */   addiu      $sp, $sp, 0x10
endlabel gr2_i2cPanelOn

nonmatching gr2_i2cPanelOff, 0x28

glabel gr2_i2cPanelOff # 13
    /* 000EB0 00000EB0 27BDFFF0 */  addiu       $sp, $sp, -0x10
    /* 000EB4 00000EB4 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 000EB8 00000EB8 0C000000 */  jal         dcb_fifowait
    /* 000EBC 00000EBC 00000000 */   nop
    /* 000EC0 00000EC0 240500FF */  addiu       $a1, $zero, 0xFF
    /* 000EC4 00000EC4 0C000000 */  jal         gr2_i2cPortWrite
    /* 000EC8 00000EC8 24040070 */   addiu      $a0, $zero, 0x70
    /* 000ECC 00000ECC DFBF0000 */  ld          $ra, 0x0($sp)
    /* 000ED0 00000ED0 03E00008 */  jr          $ra
    /* 000ED4 00000ED4 27BD0010 */   addiu      $sp, $sp, 0x10
endlabel gr2_i2cPanelOff

nonmatching gr2_i2cBlUp, 0xE0

glabel gr2_i2cBlUp, local # 14
    /* 000ED8 00000ED8 00001025 */  move        $v0, $zero
    /* 000EDC 00000EDC 8F81881C */  lw          $at, %gp_rel(.sbss + 0x1C)($gp)
    /* 000EE0 00000EE0 27BDFFC0 */  addiu       $sp, $sp, -0x40
    /* 000EE4 00000EE4 FFB00000 */  sd          $s0, 0x0($sp)
    /* 000EE8 00000EE8 10200003 */  beqz        $at, .L00000EF8
    /* 000EEC 00000EEC 00808025 */   move       $s0, $a0
    /* 000EF0 00000EF0 FFB40028 */  sd          $s4, 0x28($sp)
    /* 000EF4 00000EF4 24020008 */  addiu       $v0, $zero, 0x8
  .L00000EF8:
    /* 000EF8 00000EF8 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 000EFC 00000EFC FFB30018 */  sd          $s3, 0x18($sp)
    /* 000F00 00000F00 FFB20010 */  sd          $s2, 0x10($sp)
    /* 000F04 00000F04 345200E4 */  ori         $s2, $v0, 0xE4
    /* 000F08 00000F08 FFB40028 */  sd          $s4, 0x28($sp)
    /* 000F0C 00000F0C 2414FFFF */  addiu       $s4, $zero, -0x1
    /* 000F10 00000F10 2610FFFF */  addiu       $s0, $s0, -0x1
    /* 000F14 00000F14 1214001F */  beq         $s0, $s4, .L00000F94
    /* 000F18 00000F18 FFB10020 */   sd         $s1, 0x20($sp)
    /* 000F1C 00000F1C 345300E7 */  ori         $s3, $v0, 0xE7
    /* 000F20 00000F20 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 000F24 00000F24 10000002 */  b           .L00000F30
    /* 000F28 00000F28 345100E6 */   ori        $s1, $v0, 0xE6
  .L00000F2C:
    /* 000F2C 00000F2C 12140019 */  beq         $s0, $s4, .L00000F94
  .L00000F30:
    /* 000F30 00000F30 24040070 */   addiu      $a0, $zero, 0x70
    /* 000F34 00000F34 0C000000 */  jal         gr2_i2cPortWrite
    /* 000F38 00000F38 02202825 */   move       $a1, $s1
    /* 000F3C 00000F3C 10400013 */  beqz        $v0, .L00000F8C
    /* 000F40 00000F40 24040070 */   addiu      $a0, $zero, 0x70
    /* 000F44 00000F44 0C000000 */  jal         gr2_i2cPortWrite
    /* 000F48 00000F48 02402825 */   move       $a1, $s2
    /* 000F4C 00000F4C 1040000F */  beqz        $v0, .L00000F8C
    /* 000F50 00000F50 24040070 */   addiu      $a0, $zero, 0x70
    /* 000F54 00000F54 0C000000 */  jal         gr2_i2cPortWrite
    /* 000F58 00000F58 02202825 */   move       $a1, $s1
    /* 000F5C 00000F5C 1040000B */  beqz        $v0, .L00000F8C
    /* 000F60 00000F60 24040070 */   addiu      $a0, $zero, 0x70
    /* 000F64 00000F64 0C000000 */  jal         gr2_i2cPortWrite
    /* 000F68 00000F68 02602825 */   move       $a1, $s3
    /* 000F6C 00000F6C 10400007 */  beqz        $v0, .L00000F8C
    /* 000F70 00000F70 8F828804 */   lw         $v0, %gp_rel(.sbss + 0x4)($gp)
    /* 000F74 00000F74 2610FFFF */  addiu       $s0, $s0, -0x1
    /* 000F78 00000F78 28430064 */  slti        $v1, $v0, 0x64
    /* 000F7C 00000F7C 1060FFEB */  beqz        $v1, .L00000F2C
    /* 000F80 00000F80 24460001 */   addiu      $a2, $v0, 0x1
    /* 000F84 00000F84 1000FFE9 */  b           .L00000F2C
    /* 000F88 00000F88 AF868804 */   sw         $a2, %gp_rel(.sbss + 0x4)($gp)
  .L00000F8C:
    /* 000F8C 00000F8C 10000002 */  b           .L00000F98
    /* 000F90 00000F90 00001025 */   move       $v0, $zero
  .L00000F94:
    /* 000F94 00000F94 24020001 */  addiu       $v0, $zero, 0x1
  .L00000F98:
    /* 000F98 00000F98 DFB00000 */  ld          $s0, 0x0($sp)
    /* 000F9C 00000F9C DFB10020 */  ld          $s1, 0x20($sp)
    /* 000FA0 00000FA0 DFB20010 */  ld          $s2, 0x10($sp)
    /* 000FA4 00000FA4 DFBF0008 */  ld          $ra, 0x8($sp)
    /* 000FA8 00000FA8 DFB30018 */  ld          $s3, 0x18($sp)
    /* 000FAC 00000FAC DFB40028 */  ld          $s4, 0x28($sp)
    /* 000FB0 00000FB0 03E00008 */  jr          $ra
    /* 000FB4 00000FB4 27BD0040 */   addiu      $sp, $sp, 0x40
endlabel gr2_i2cBlUp

nonmatching gr2_i2cBlDown, 0xE0

glabel gr2_i2cBlDown, local # 15
    /* 000FB8 00000FB8 00001025 */  move        $v0, $zero
    /* 000FBC 00000FBC 8F81881C */  lw          $at, %gp_rel(.sbss + 0x1C)($gp)
    /* 000FC0 00000FC0 27BDFFC0 */  addiu       $sp, $sp, -0x40
    /* 000FC4 00000FC4 FFB00000 */  sd          $s0, 0x0($sp)
    /* 000FC8 00000FC8 10200003 */  beqz        $at, .L00000FD8
    /* 000FCC 00000FCC 00808025 */   move       $s0, $a0
    /* 000FD0 00000FD0 FFB40028 */  sd          $s4, 0x28($sp)
    /* 000FD4 00000FD4 24020008 */  addiu       $v0, $zero, 0x8
  .L00000FD8:
    /* 000FD8 00000FD8 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 000FDC 00000FDC FFB30018 */  sd          $s3, 0x18($sp)
    /* 000FE0 00000FE0 FFB20010 */  sd          $s2, 0x10($sp)
    /* 000FE4 00000FE4 345200E0 */  ori         $s2, $v0, 0xE0
    /* 000FE8 00000FE8 FFB40028 */  sd          $s4, 0x28($sp)
    /* 000FEC 00000FEC 2414FFFF */  addiu       $s4, $zero, -0x1
    /* 000FF0 00000FF0 2610FFFF */  addiu       $s0, $s0, -0x1
    /* 000FF4 00000FF4 1214001F */  beq         $s0, $s4, .L00001074
    /* 000FF8 00000FF8 FFB10020 */   sd         $s1, 0x20($sp)
    /* 000FFC 00000FFC 345300E7 */  ori         $s3, $v0, 0xE7
    /* 001000 00001000 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 001004 00001004 10000003 */  b           .L00001014
    /* 001008 00001008 345100E2 */   ori        $s1, $v0, 0xE2
  .L0000100C:
    /* 00100C 0000100C AF838804 */  sw          $v1, %gp_rel(.sbss + 0x4)($gp)
  .L00001010:
    /* 001010 00001010 12140018 */  beq         $s0, $s4, .L00001074
  .L00001014:
    /* 001014 00001014 24040070 */   addiu      $a0, $zero, 0x70
    /* 001018 00001018 0C000000 */  jal         gr2_i2cPortWrite
    /* 00101C 0000101C 02202825 */   move       $a1, $s1
    /* 001020 00001020 10400012 */  beqz        $v0, .L0000106C
    /* 001024 00001024 24040070 */   addiu      $a0, $zero, 0x70
    /* 001028 00001028 0C000000 */  jal         gr2_i2cPortWrite
    /* 00102C 0000102C 02402825 */   move       $a1, $s2
    /* 001030 00001030 1040000E */  beqz        $v0, .L0000106C
    /* 001034 00001034 24040070 */   addiu      $a0, $zero, 0x70
    /* 001038 00001038 0C000000 */  jal         gr2_i2cPortWrite
    /* 00103C 0000103C 02202825 */   move       $a1, $s1
    /* 001040 00001040 1040000A */  beqz        $v0, .L0000106C
    /* 001044 00001044 24040070 */   addiu      $a0, $zero, 0x70
    /* 001048 00001048 0C000000 */  jal         gr2_i2cPortWrite
    /* 00104C 0000104C 02602825 */   move       $a1, $s3
    /* 001050 00001050 10400006 */  beqz        $v0, .L0000106C
    /* 001054 00001054 8F828804 */   lw         $v0, %gp_rel(.sbss + 0x4)($gp)
    /* 001058 00001058 2610FFFF */  addiu       $s0, $s0, -0x1
    /* 00105C 0000105C 1840FFEC */  blez        $v0, .L00001010
    /* 001060 00001060 00000000 */   nop
    /* 001064 00001064 1000FFE9 */  b           .L0000100C
    /* 001068 00001068 2443FFFF */   addiu      $v1, $v0, -0x1
  .L0000106C:
    /* 00106C 0000106C 10000002 */  b           .L00001078
    /* 001070 00001070 00001025 */   move       $v0, $zero
  .L00001074:
    /* 001074 00001074 24020001 */  addiu       $v0, $zero, 0x1
  .L00001078:
    /* 001078 00001078 DFB00000 */  ld          $s0, 0x0($sp)
    /* 00107C 0000107C DFB10020 */  ld          $s1, 0x20($sp)
    /* 001080 00001080 DFB20010 */  ld          $s2, 0x10($sp)
    /* 001084 00001084 DFBF0008 */  ld          $ra, 0x8($sp)
    /* 001088 00001088 DFB30018 */  ld          $s3, 0x18($sp)
    /* 00108C 0000108C DFB40028 */  ld          $s4, 0x28($sp)
    /* 001090 00001090 03E00008 */  jr          $ra
    /* 001094 00001094 27BD0040 */   addiu      $sp, $sp, 0x40
endlabel gr2_i2cBlDown

nonmatching gr2_i2cAudioVolLeft, 0x68

glabel gr2_i2cAudioVolLeft, local # 16
    /* 001098 00001098 00800825 */  move        $at, $a0
    /* 00109C 0000109C 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 0010A0 000010A0 FFA40008 */  sd          $a0, 0x8($sp)
    /* 0010A4 000010A4 24040082 */  addiu       $a0, $zero, 0x82
    /* 0010A8 000010A8 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 0010AC 000010AC 0C000000 */  jal         gr2_i2cStart
    /* 0010B0 000010B0 AF818808 */   sw         $at, %gp_rel(.sbss + 0x8)($gp)
    /* 0010B4 000010B4 1040000F */  beqz        $v0, .L000010F4
    /* 0010B8 000010B8 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0010BC 000010BC 0C000000 */  jal         gr2_i2cSend
    /* 0010C0 000010C0 00002025 */   move       $a0, $zero
    /* 0010C4 000010C4 1040000B */  beqz        $v0, .L000010F4
    /* 0010C8 000010C8 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0010CC 000010CC 0C000000 */  jal         gr2_i2cSend
    /* 0010D0 000010D0 DFA40008 */   ld         $a0, 0x8($sp)
    /* 0010D4 000010D4 10400007 */  beqz        $v0, .L000010F4
    /* 0010D8 000010D8 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0010DC 000010DC 0C000000 */  jal         gr2_i2cStop
    /* 0010E0 000010E0 00000000 */   nop
    /* 0010E4 000010E4 10400003 */  beqz        $v0, .L000010F4
    /* 0010E8 000010E8 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0010EC 000010EC 10000002 */  b           .L000010F8
    /* 0010F0 000010F0 24020001 */   addiu      $v0, $zero, 0x1
  .L000010F4:
    /* 0010F4 000010F4 00001025 */  move        $v0, $zero
  .L000010F8:
    /* 0010F8 000010F8 03E00008 */  jr          $ra
    /* 0010FC 000010FC 27BD0020 */   addiu      $sp, $sp, 0x20
endlabel gr2_i2cAudioVolLeft

nonmatching gr2_i2cAudioVolRight, 0x68

glabel gr2_i2cAudioVolRight, local # 17
    /* 001100 00001100 00800825 */  move        $at, $a0
    /* 001104 00001104 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 001108 00001108 FFA40008 */  sd          $a0, 0x8($sp)
    /* 00110C 0000110C 24040082 */  addiu       $a0, $zero, 0x82
    /* 001110 00001110 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 001114 00001114 0C000000 */  jal         gr2_i2cStart
    /* 001118 00001118 AF81880C */   sw         $at, %gp_rel(.sbss + 0xC)($gp)
    /* 00111C 0000111C 1040000F */  beqz        $v0, .L0000115C
    /* 001120 00001120 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 001124 00001124 0C000000 */  jal         gr2_i2cSend
    /* 001128 00001128 24040001 */   addiu      $a0, $zero, 0x1
    /* 00112C 0000112C 1040000B */  beqz        $v0, .L0000115C
    /* 001130 00001130 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 001134 00001134 0C000000 */  jal         gr2_i2cSend
    /* 001138 00001138 DFA40008 */   ld         $a0, 0x8($sp)
    /* 00113C 0000113C 10400007 */  beqz        $v0, .L0000115C
    /* 001140 00001140 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 001144 00001144 0C000000 */  jal         gr2_i2cStop
    /* 001148 00001148 00000000 */   nop
    /* 00114C 0000114C 10400003 */  beqz        $v0, .L0000115C
    /* 001150 00001150 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 001154 00001154 10000002 */  b           .L00001160
    /* 001158 00001158 24020001 */   addiu      $v0, $zero, 0x1
  .L0000115C:
    /* 00115C 0000115C 00001025 */  move        $v0, $zero
  .L00001160:
    /* 001160 00001160 03E00008 */  jr          $ra
    /* 001164 00001164 27BD0020 */   addiu      $sp, $sp, 0x20
endlabel gr2_i2cAudioVolRight

nonmatching gr2_i2cAudioBass, 0x68

glabel gr2_i2cAudioBass, local # 18
    /* 001168 00001168 00800825 */  move        $at, $a0
    /* 00116C 0000116C 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 001170 00001170 FFA40008 */  sd          $a0, 0x8($sp)
    /* 001174 00001174 24040082 */  addiu       $a0, $zero, 0x82
    /* 001178 00001178 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 00117C 0000117C 0C000000 */  jal         gr2_i2cStart
    /* 001180 00001180 AF818810 */   sw         $at, %gp_rel(.sbss + 0x10)($gp)
    /* 001184 00001184 1040000F */  beqz        $v0, .L000011C4
    /* 001188 00001188 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 00118C 0000118C 0C000000 */  jal         gr2_i2cSend
    /* 001190 00001190 24040002 */   addiu      $a0, $zero, 0x2
    /* 001194 00001194 1040000B */  beqz        $v0, .L000011C4
    /* 001198 00001198 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 00119C 0000119C 0C000000 */  jal         gr2_i2cSend
    /* 0011A0 000011A0 DFA40008 */   ld         $a0, 0x8($sp)
    /* 0011A4 000011A4 10400007 */  beqz        $v0, .L000011C4
    /* 0011A8 000011A8 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0011AC 000011AC 0C000000 */  jal         gr2_i2cStop
    /* 0011B0 000011B0 00000000 */   nop
    /* 0011B4 000011B4 10400003 */  beqz        $v0, .L000011C4
    /* 0011B8 000011B8 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0011BC 000011BC 10000002 */  b           .L000011C8
    /* 0011C0 000011C0 24020001 */   addiu      $v0, $zero, 0x1
  .L000011C4:
    /* 0011C4 000011C4 00001025 */  move        $v0, $zero
  .L000011C8:
    /* 0011C8 000011C8 03E00008 */  jr          $ra
    /* 0011CC 000011CC 27BD0020 */   addiu      $sp, $sp, 0x20
endlabel gr2_i2cAudioBass

nonmatching gr2_i2cAudioTreble, 0x68

glabel gr2_i2cAudioTreble, local # 19
    /* 0011D0 000011D0 00800825 */  move        $at, $a0
    /* 0011D4 000011D4 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 0011D8 000011D8 FFA40008 */  sd          $a0, 0x8($sp)
    /* 0011DC 000011DC 24040082 */  addiu       $a0, $zero, 0x82
    /* 0011E0 000011E0 FFBF0000 */  sd          $ra, 0x0($sp)
    /* 0011E4 000011E4 0C000000 */  jal         gr2_i2cStart
    /* 0011E8 000011E8 AF818814 */   sw         $at, %gp_rel(.sbss + 0x14)($gp)
    /* 0011EC 000011EC 1040000F */  beqz        $v0, .L0000122C
    /* 0011F0 000011F0 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 0011F4 000011F4 0C000000 */  jal         gr2_i2cSend
    /* 0011F8 000011F8 24040003 */   addiu      $a0, $zero, 0x3
    /* 0011FC 000011FC 1040000B */  beqz        $v0, .L0000122C
    /* 001200 00001200 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 001204 00001204 0C000000 */  jal         gr2_i2cSend
    /* 001208 00001208 DFA40008 */   ld         $a0, 0x8($sp)
    /* 00120C 0000120C 10400007 */  beqz        $v0, .L0000122C
    /* 001210 00001210 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 001214 00001214 0C000000 */  jal         gr2_i2cStop
    /* 001218 00001218 00000000 */   nop
    /* 00121C 0000121C 10400003 */  beqz        $v0, .L0000122C
    /* 001220 00001220 DFBF0000 */   ld         $ra, 0x0($sp)
    /* 001224 00001224 10000002 */  b           .L00001230
    /* 001228 00001228 24020001 */   addiu      $v0, $zero, 0x1
  .L0000122C:
    /* 00122C 0000122C 00001025 */  move        $v0, $zero
  .L00001230:
    /* 001230 00001230 03E00008 */  jr          $ra
    /* 001234 00001234 27BD0020 */   addiu      $sp, $sp, 0x20
endlabel gr2_i2cAudioTreble

nonmatching gr2_i2cAudioSwitch, 0x84

glabel gr2_i2cAudioSwitch, local # 20
    /* 001238 00001238 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 00123C 0000123C 30810020 */  andi        $at, $a0, 0x20
    /* 001240 00001240 1020001A */  beqz        $at, .L000012AC
    /* 001244 00001244 00801025 */   move       $v0, $a0
    /* 001248 00001248 24030001 */  addiu       $v1, $zero, 0x1
    /* 00124C 0000124C FFA20000 */  sd          $v0, 0x0($sp)
    /* 001250 00001250 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 001254 00001254 AF838818 */  sw          $v1, %gp_rel(.sbss + 0x18)($gp)
  .L00001258:
    /* 001258 00001258 0C000000 */  jal         gr2_i2cStart
    /* 00125C 0000125C 24040082 */   addiu      $a0, $zero, 0x82
    /* 001260 00001260 1040000F */  beqz        $v0, .L000012A0
    /* 001264 00001264 DFBF0008 */   ld         $ra, 0x8($sp)
    /* 001268 00001268 0C000000 */  jal         gr2_i2cSend
    /* 00126C 0000126C 24040008 */   addiu      $a0, $zero, 0x8
    /* 001270 00001270 1040000B */  beqz        $v0, .L000012A0
    /* 001274 00001274 DFBF0008 */   ld         $ra, 0x8($sp)
    /* 001278 00001278 0C000000 */  jal         gr2_i2cSend
    /* 00127C 0000127C DFA40000 */   ld         $a0, 0x0($sp)
    /* 001280 00001280 10400007 */  beqz        $v0, .L000012A0
    /* 001284 00001284 DFBF0008 */   ld         $ra, 0x8($sp)
    /* 001288 00001288 0C000000 */  jal         gr2_i2cStop
    /* 00128C 0000128C 00000000 */   nop
    /* 001290 00001290 10400003 */  beqz        $v0, .L000012A0
    /* 001294 00001294 DFBF0008 */   ld         $ra, 0x8($sp)
    /* 001298 00001298 10000002 */  b           .L000012A4
    /* 00129C 0000129C 24020001 */   addiu      $v0, $zero, 0x1
  .L000012A0:
    /* 0012A0 000012A0 00001025 */  move        $v0, $zero
  .L000012A4:
    /* 0012A4 000012A4 03E00008 */  jr          $ra
    /* 0012A8 000012A8 27BD0020 */   addiu      $sp, $sp, 0x20
  .L000012AC:
    /* 0012AC 000012AC FFA20000 */  sd          $v0, 0x0($sp)
    /* 0012B0 000012B0 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 0012B4 000012B4 1000FFE8 */  b           .L00001258
    /* 0012B8 000012B8 AF808818 */   sw         $zero, %gp_rel(.sbss + 0x18)($gp)
endlabel gr2_i2cAudioSwitch

nonmatching gr2_i2cSetBit, 0x44

glabel gr2_i2cSetBit, local # 21
    /* 0012BC 000012BC 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 0012C0 000012C0 10800009 */  beqz        $a0, .L000012E8
    /* 0012C4 000012C4 FFBF0000 */   sd         $ra, 0x0($sp)
    /* 0012C8 000012C8 240500EF */  addiu       $a1, $zero, 0xEF
    /* 0012CC 000012CC 24040070 */  addiu       $a0, $zero, 0x70
    /* 0012D0 000012D0 24010001 */  addiu       $at, $zero, 0x1
    /* 0012D4 000012D4 0C000000 */  jal         gr2_i2cPortWrite
    /* 0012D8 000012D8 AF81881C */   sw         $at, %gp_rel(.sbss + 0x1C)($gp)
    /* 0012DC 000012DC DFBF0000 */  ld          $ra, 0x0($sp)
  .L000012E0:
    /* 0012E0 000012E0 03E00008 */  jr          $ra
    /* 0012E4 000012E4 27BD0020 */   addiu      $sp, $sp, 0x20
  .L000012E8:
    /* 0012E8 000012E8 240500E7 */  addiu       $a1, $zero, 0xE7
    /* 0012EC 000012EC 24040070 */  addiu       $a0, $zero, 0x70
    /* 0012F0 000012F0 0C000000 */  jal         gr2_i2cPortWrite
    /* 0012F4 000012F4 AF80881C */   sw         $zero, %gp_rel(.sbss + 0x1C)($gp)
    /* 0012F8 000012F8 1000FFF9 */  b           .L000012E0
    /* 0012FC 000012FC DFBF0000 */   ld         $ra, 0x0($sp)
endlabel gr2_i2cSetBit

nonmatching gr2_i2c_command, 0x1BC

glabel gr2_i2c_command # 22
    /* 001300 00001300 8F818800 */  lw          $at, %gp_rel(.sbss)($gp)
    /* 001304 00001304 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 001308 00001308 FFB70000 */  sd          $s7, 0x0($sp)
    /* 00130C 0000130C 14200005 */  bnez        $at, .L00001324
    /* 001310 00001310 0080B825 */   move       $s7, $a0
    /* 001314 00001314 24020013 */  addiu       $v0, $zero, 0x13
    /* 001318 00001318 DFB70000 */  ld          $s7, 0x0($sp)
  .L0000131C:
    /* 00131C 0000131C 03E00008 */  jr          $ra
    /* 001320 00001320 27BD0020 */   addiu      $sp, $sp, 0x20
  .L00001324:
    /* 001324 00001324 FFBF0008 */  sd          $ra, 0x8($sp)
    /* 001328 00001328 0C000000 */  jal         dcb_fifowait
    /* 00132C 0000132C 00000000 */   nop
    /* 001330 00001330 DFBF0008 */  ld          $ra, 0x8($sp)
    /* 001334 00001334 8EE60000 */  lw          $a2, 0x0($s7)
    /* 001338 00001338 3C050000 */  lui         $a1, 0x0
    /* 00133C 0000133C 24A50020 */  addiu       $a1, $a1, %lo(jpt_000019E8)
    /* 001340 00001340 00061080 */  sll         $v0, $a2, 2
    /* 001344 00001344 2CC30011 */  sltiu       $v1, $a2, 0x11
    /* 001348 00001348 10600005 */  beqz        $v1, .L00001360
    /* 00134C 0000134C 00451021 */   addu       $v0, $v0, $a1
    /* 001350 00001350 8C470000 */  lw          $a3, 0x0($v0)
    /* 001354 00001354 8F838814 */  lw          $v1, %gp_rel(.sbss + 0x14)($gp)
    /* 001358 00001358 00E00008 */  jr          $a3
    /* 00135C 0000135C 8F85881C */   lw         $a1, %gp_rel(.sbss + 0x1C)($gp)
  .L00001360:
    /* 001360 00001360 24040004 */  addiu       $a0, $zero, 0x4
    /* 001364 00001364 DFB70000 */  ld          $s7, 0x0($sp)
    /* 001368 00001368 3C050000 */  lui         $a1, (0x0 >> 16)
    /* 00136C 0000136C 0C000000 */  jal         cmn_err
    /* 001370 00001370 24A50000 */   addiu      $a1, $a1, %lo(RO_STR_000019C8)
    /* 001374 00001374 24020016 */  addiu       $v0, $zero, 0x16
    /* 001378 00001378 1000FFE8 */  b           .L0000131C
    /* 00137C 0000137C DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L00001380
    /* 001380 00001380 0C000000 */  jal         gr2_i2cPanelOn
    /* 001384 00001384 00000000 */   nop
    /* 001388 00001388 AEE20008 */  sw          $v0, 0x8($s7)
    /* 00138C 0000138C 10000003 */  b           .L0000139C
    /* 001390 00001390 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L00001394
    /* 001394 00001394 8F87880C */  lw          $a3, %gp_rel(.sbss + 0xC)($gp)
    /* 001398 00001398 AEE70008 */  sw          $a3, 0x8($s7)
  .L0000139C:
    /* 00139C 0000139C 00001025 */  move        $v0, $zero
    /* 0013A0 000013A0 1000FFDE */  b           .L0000131C
    /* 0013A4 000013A4 DFB70000 */   ld         $s7, 0x0($sp)
  jlabel .L000013A8
    /* 0013A8 000013A8 0C000000 */  jal         gr2_i2cPanelOff
    /* 0013AC 000013AC 00000000 */   nop
    /* 0013B0 000013B0 AEE20008 */  sw          $v0, 0x8($s7)
    /* 0013B4 000013B4 1000FFF9 */  b           .L0000139C
    /* 0013B8 000013B8 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L000013BC
    /* 0013BC 000013BC 8EE40004 */  lw          $a0, 0x4($s7)
    /* 0013C0 000013C0 0C000000 */  jal         gr2_i2cBlUp
    /* 0013C4 000013C4 8C840000 */   lw         $a0, 0x0($a0)
    /* 0013C8 000013C8 AEE20008 */  sw          $v0, 0x8($s7)
    /* 0013CC 000013CC 1000FFF3 */  b           .L0000139C
    /* 0013D0 000013D0 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L000013D4
    /* 0013D4 000013D4 8EE40004 */  lw          $a0, 0x4($s7)
    /* 0013D8 000013D8 0C000000 */  jal         gr2_i2cBlDown
    /* 0013DC 000013DC 8C840000 */   lw         $a0, 0x0($a0)
    /* 0013E0 000013E0 AEE20008 */  sw          $v0, 0x8($s7)
    /* 0013E4 000013E4 1000FFED */  b           .L0000139C
    /* 0013E8 000013E8 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L000013EC
    /* 0013EC 000013EC 8EE40004 */  lw          $a0, 0x4($s7)
    /* 0013F0 000013F0 0C000000 */  jal         gr2_i2cAudioVolLeft
    /* 0013F4 000013F4 8C840000 */   lw         $a0, 0x0($a0)
    /* 0013F8 000013F8 AEE20008 */  sw          $v0, 0x8($s7)
    /* 0013FC 000013FC 1000FFE7 */  b           .L0000139C
    /* 001400 00001400 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L00001404
    /* 001404 00001404 8EE40004 */  lw          $a0, 0x4($s7)
    /* 001408 00001408 0C000000 */  jal         gr2_i2cAudioVolRight
    /* 00140C 0000140C 8C840000 */   lw         $a0, 0x0($a0)
    /* 001410 00001410 AEE20008 */  sw          $v0, 0x8($s7)
    /* 001414 00001414 1000FFE1 */  b           .L0000139C
    /* 001418 00001418 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L0000141C
    /* 00141C 0000141C 8EE40004 */  lw          $a0, 0x4($s7)
    /* 001420 00001420 0C000000 */  jal         gr2_i2cAudioBass
    /* 001424 00001424 8C840000 */   lw         $a0, 0x0($a0)
    /* 001428 00001428 AEE20008 */  sw          $v0, 0x8($s7)
    /* 00142C 0000142C 1000FFDB */  b           .L0000139C
    /* 001430 00001430 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L00001434
    /* 001434 00001434 8EE40004 */  lw          $a0, 0x4($s7)
    /* 001438 00001438 0C000000 */  jal         gr2_i2cAudioTreble
    /* 00143C 0000143C 8C840000 */   lw         $a0, 0x0($a0)
    /* 001440 00001440 AEE20008 */  sw          $v0, 0x8($s7)
    /* 001444 00001444 1000FFD5 */  b           .L0000139C
    /* 001448 00001448 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L0000144C
    /* 00144C 0000144C 8EE40004 */  lw          $a0, 0x4($s7)
    /* 001450 00001450 0C000000 */  jal         gr2_i2cAudioSwitch
    /* 001454 00001454 8C840000 */   lw         $a0, 0x0($a0)
    /* 001458 00001458 AEE20008 */  sw          $v0, 0x8($s7)
    /* 00145C 0000145C 1000FFCF */  b           .L0000139C
    /* 001460 00001460 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L00001464
    /* 001464 00001464 8F858804 */  lw          $a1, %gp_rel(.sbss + 0x4)($gp)
    /* 001468 00001468 1000FFCC */  b           .L0000139C
    /* 00146C 0000146C AEE50008 */   sw         $a1, 0x8($s7)
  jlabel .L00001470
    /* 001470 00001470 8F878808 */  lw          $a3, %gp_rel(.sbss + 0x8)($gp)
    /* 001474 00001474 1000FFC9 */  b           .L0000139C
    /* 001478 00001478 AEE70008 */   sw         $a3, 0x8($s7)
  jlabel .L0000147C
    /* 00147C 0000147C 8F818810 */  lw          $at, %gp_rel(.sbss + 0x10)($gp)
    /* 001480 00001480 1000FFC6 */  b           .L0000139C
    /* 001484 00001484 AEE10008 */   sw         $at, 0x8($s7)
  jlabel .L00001488
    /* 001488 00001488 1000FFC4 */  b           .L0000139C
    /* 00148C 0000148C AEE30008 */   sw         $v1, 0x8($s7)
  jlabel .L00001490
    /* 001490 00001490 8F858818 */  lw          $a1, %gp_rel(.sbss + 0x18)($gp)
    /* 001494 00001494 1000FFC1 */  b           .L0000139C
    /* 001498 00001498 AEE50008 */   sw         $a1, 0x8($s7)
  jlabel .L0000149C
    /* 00149C 0000149C 8EE40004 */  lw          $a0, 0x4($s7)
    /* 0014A0 000014A0 0C000000 */  jal         gr2_i2cSetBit
    /* 0014A4 000014A4 8C840000 */   lw         $a0, 0x0($a0)
    /* 0014A8 000014A8 AEE20008 */  sw          $v0, 0x8($s7)
    /* 0014AC 000014AC 1000FFBB */  b           .L0000139C
    /* 0014B0 000014B0 DFBF0008 */   ld         $ra, 0x8($sp)
  jlabel .L000014B4
    /* 0014B4 000014B4 1000FFB9 */  b           .L0000139C
    /* 0014B8 000014B8 AEE50008 */   sw         $a1, 0x8($s7)
endlabel gr2_i2c_command
