.include "macro.inc"

.section .data

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching Gr2Boards

/* static variable */
dlabel Gr2Boards
    /* 005A88 00005A88 BF000000 */ .word 0xBF000000
    /* 005A8C 00005A8C 00000000 */ .word 0x00000000
    /* 005A90 00005A90 00000000 */ .word Gr2Boards
    /* 005A94 00005A94 00000000 */ .word 0x00000000
    /* 005A98 00005A98 00000002 */ .word 0x00000002
    /* 005A9C 00005A9C 00000000 */ .word 0x00000000
    /* 005AA0 00005AA0 00000008 */ .word 0x00000008
    /* 005AA4 00005AA4 BF400000 */ .word 0xBF400000
    /* 005AA8 00005AA8 00000000 */ .word 0x00000000
    /* 005AAC 00005AAC 0000003C */ .word B_00005AC4
    /* 005AB0 00005AB0 00000000 */ .word 0x00000000
    /* 005AB4 00005AB4 00000000 */ .word 0x00000000
    /* 005AB8 00005AB8 00000001 */ .word 0x00000001
    /* 005ABC 00005ABC 00000010 */ .word 0x00000010
    /* 005AC0 00005AC0 00000000 */ .word 0x00000000

nonmatching B_00005AC4

/* static variable */
dlabel B_00005AC4
    /* 005AC4 00005AC4 00000000 */ .word 0x00000000
    /* 005AC8 00005AC8 00000000 */ .word 0x00000000
    /* 005ACC 00005ACC 00000000 */ .word 0x00000000
    /* 005AD0 00005AD0 00000000 */ .word 0x00000000
    /* 005AD4 00005AD4 00000000 */ .word 0x00000000
    /* 005AD8 00005AD8 00000000 */ .word 0x00000000
enddlabel Gr2Boards

nonmatching B_00005ADC

/* Automatically generated and unreferenced pad */
dlabel B_00005ADC
    /* 005ADC 00005ADC 00000000 */ .word 0x00000000
enddlabel B_00005ADC

nonmatching genlockclk

dlabel genlockclk
    /* 005AE0 00005AE0 C4001322 */ .word 0xC4001322
    /* 005AE4 00005AE4 30425060 */ .word 0x30425060
    /* 005AE8 00005AE8 708094A6 */ .word 0x708094A6
    /* 005AEC 00005AEC B4D9E0F0 */ .word 0xB4D9E0F0
    /* 005AF0 00005AF0 */ .byte 0xC4
enddlabel genlockclk

nonmatching B_00005AF1

/* Automatically generated and unreferenced pad */
dlabel B_00005AF1
    /* 005AF1 00005AF1 */ .byte 0x00
    /* 005AF2 00005AF2 */ .short 0x0000
    /* 005AF4 00005AF4 00000000 */ .word 0x00000000
    /* 005AF8 00005AF8 00000000 */ .word Gr2Info
    /* 005AFC 00005AFC 00000000 */ .word Gr2Attach
    /* 005B00 00005B00 00000000 */ .word Gr2Detach
    /* 005B04 00005B04 00000000 */ .word Gr2Initialize
    /* 005B08 00005B08 00000000 */ .word Gr2Download
    /* 005B0C 00005B0C 00000000 */ .word Gr2Start
    /* 005B10 00005B10 00000000 */ .word Gr2PositionCursor
    /* 005B14 00005B14 00000000 */ .word 0x00000000
    /* 005B18 00005B18 00000000 */ .word Gr2CreateDDRN
    /* 005B1C 00005B1C 00000000 */ .word Gr2DestroyDDRN
    /* 005B20 00005B20 00000000 */ .word Gr2ValidateClip
    /* 005B24 00005B24 00000000 */ .word Gr2SetNullClip
    /* 005B28 00005B28 00000000 */ .word Gr2MapGfx
    /* 005B2C 00005B2C 00000000 */ .word Gr2UnMapGfx
    /* 005B30 00005B30 00000000 */ .word Gr2InvalTLB
    /* 005B34 00005B34 00000000 */ .word Gr2PcxSwap
    /* 005B38 00005B38 00000000 */ .word Gr2PcxSwitch
    /* 005B3C 00005B3C 00000000 */ .word Gr2SchedSwapBuf
    /* 005B40 00005B40 00000000 */ .word Gr2UnSchedSwapBuf
    /* 005B44 00005B44 00000000 */ .word Gr2SchedRetraceEvent
    /* 005B48 00005B48 00000000 */ .word Gr2SetDisplayMode
    /* 005B4C 00005B4C 00000000 */ .word Gr2SchedMgrSwapBuf
    /* 005B50 00005B50 00000000 */ .word Gr2Suspend
    /* 005B54 00005B54 00000000 */ .word Gr2Resume
    /* 005B58 00005B58 00000000 */ .word 0x00000000
    /* 005B5C 00005B5C 00000000 */ .word Gr2Private
    /* 005B60 00005B60 00000000 */ .word 0x00000000
    /* 005B64 00005B64 00000000 */ .word 0x00000000
enddlabel B_00005AF1
