.include "macro.inc"

.section .bss

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching Gr2Boards, 0x3C

/* static variable */
dlabel Gr2Boards
    /* 00005A88 */ .space 0x3C

nonmatching B_00005AC4, 0x18

/* static variable */
dlabel B_00005AC4
    /* 00005AC4 */ .space 0x18

nonmatching B_00005ADC, 0x4

/* Automatically generated and unreferenced pad */
dlabel B_00005ADC
    /* 00005ADC */ .space 0x04

nonmatching genlockclk, 0x11

dlabel genlockclk
    /* 00005AE0 */ .space 0x11
enddlabel genlockclk

nonmatching B_00005AF1, 0xF

/* Automatically generated and unreferenced pad */
dlabel B_00005AF1
    /* 00005AF1 */ .space 0x0F
