.include "macro.inc"

.section .sdata

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching D_00005A68

/* static variable */
dlabel D_00005A68
    /* 005A68 00005A68 00000000 */ .word 0x00000000
    /* 005A6C 00005A6C 00000000 */ .word 0x00000000
    /* 005A70 00005A70 00000041 */ .word 0x00000041
    /* 005A74 00005A74 00000000 */ .word 0x00000000
    /* 005A78 00005A78 80000000 */ .word 0x80000000
    /* 005A7C 00005A7C 00000000 */ .word 0x00000000
    /* 005A80 00005A80 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel D_00005A68
