.include "macro.inc"

.section .data

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching gr2_htp_fncs

dlabel gr2_htp_fncs
    /* 000FA0 00000FA0 00000000 */ .word Gr2TpInit
    /* 000FA4 00000FA4 00000000 */ .word Gr2TpMapcolor
    /* 000FA8 00000FA8 00000000 */ .word Gr2TpColor
    /* 000FAC 00000FAC 00000000 */ .word Gr2TpSboxfi
    /* 000FB0 00000FB0 00000000 */ .word Gr2TpPnt2i
    /* 000FB4 00000FB4 00000000 */ .word Gr2TpDrawBitmap
    /* 000FB8 00000FB8 00000000 */ .word Gr2TpCmov2i
    /* 000FBC 00000FBC 00000000 */ .word Gr2TpUnblank
    /* 000FC0 00000FC0 00000000 */ .word Gr2TpGetDesc
    /* 000FC4 00000FC4 00000000 */ .word 0x00000000
enddlabel gr2_htp_fncs
