.include "macro.inc"

.section .srdata

.align 4

/* Generated by spimdisasm 1.42.0 */

.align 2
nonmatching B_STR_000034C0

dlabel B_STR_000034C0
    /* 0034C0 000034C0 */ .asciz "GR2"
    /* 47523200 */
.align 2
enddlabel B_STR_000034C0
