.include "macro.inc"

.section .lit8

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching B_000034B8

dlabel B_000034B8
    /* 0034B8 000034B8 FFFFFFFF */ .word 0xFFFFFFFF
    /* 0034BC 000034BC DEADBEEF */ .word 0xDEADBEEF
enddlabel B_000034B8
