.include "macro.inc"

.section .bss

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching frtableDID, 0x320

/* static variable */
dlabel frtableDID
    /* 00003198 */ .space 0x320

nonmatching B_000034B8, 0x8

dlabel B_000034B8
    /* 000034B8 */ .space 0x08

.align 2
nonmatching B_STR_000034C0, 0x70

dlabel B_STR_000034C0
    /* 000034C0 */ .space 0x70

nonmatching B_00003530, 0x468

dlabel B_00003530
    /* 00003530 */ .space 0x468

nonmatching ltableDID, 0x10

dlabel ltableDID
    /* 00003998 */ .space 0x10
enddlabel ltableDID
