.include "macro.inc"

.section .sdata

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching D_00001F54

dlabel D_00001F54
    /* 001F54 00001F54 00000000 */ .word 0x00000000
    /* 001F58 00001F58 00001F40 */ .word 0x00001F40
enddlabel D_00001F54
