.include "macro.inc"

.section .srdata

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching RO_00002238

/* static variable */
dlabel RO_00002238
    /* 002238 00002238 25732573 */ .word 0x25732573
enddlabel RO_00002238
