#!/bin/sh
#
# startgfx.sh
#
# start the window system
#
#
# Copyright 1991, Silicon Graphics, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of Silicon Graphics, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of Silicon Graphics, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished -
# rights reserved under the Copyright Laws of the United States.
#
# $Revision: 1.10 $
#

/etc/chkconfig windowsystem on

if who -lu | grep "[ 	]tport[ 	]" > /dev/null
then
	if sed '/^tp:/ s/:respawn:/:off:/' > /etc/inittab.$$ < /etc/inittab && [ -s /etc/inittab.$$ ]
	then
		sync
		mv /etc/inittab.$$ /etc/inittab
		sync
		telinit q
	else
		rm /etc/inittab.$$
		echo "Warning: $0 unable to turn off textport getty"
	fi
fi

/etc/killall -HUP xdm > /dev/null 2>&1
ret=$?
if [ $ret -eq 0 ]; then
	/bin/echo "Sent SIGHUP to xdm"
	exit
fi
echo "Starting xdm"
exec /usr/bin/X11/xdm
