.include "macro.inc"

.section .srdata

.align 4

/* Generated by spimdisasm 1.42.0 */

.align 2
nonmatching B_STR_00004968

/* static variable */
dlabel B_STR_00004968
    /* 004968 00004968 */ .asciz "Gfx"
    /* 47667800 */
.align 2
.align 2
    /* 00496C 0000496C */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 004970 00004970 */ .asciz "Gfx"
    /* 47667800 */
.align 2
.align 2
    /* 004974 00004974 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel B_STR_00004968

.align 2
nonmatching B_STR_00004978

/* static variable */
dlabel B_STR_00004978
    /* 004978 00004978 */ .asciz "ggt"
    /* 67677400 */
.align 2
.align 2
    /* 00497C 0000497C */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 004980 00004980 */ .asciz "ggpl"
    /* 6767706C00000000 */
.align 2
.align 2
    /* 004988 00004988 */ .asciz "glw"
    /* 676C7700 */
.align 2
.align 2
    /* 00498C 0000498C */ .asciz ""
    /* 00000000 */
.align 2
.align 2
    /* 004990 00004990 */ .asciz "gfxl"
    /* 6766786C00000000 */
.align 2
enddlabel B_STR_00004978

.align 2
nonmatching RO_STR_00004998

/* static variable */
dlabel RO_STR_00004998
    /* 004998 00004998 */ .asciz "gfxinfo"
    /* 676678696E666F00 */
.align 2
.align 2
    /* 0049A0 000049A0 */ .asciz "gfx"
    /* 67667800 */
.align 2
enddlabel RO_STR_00004998
