.include "macro.inc"

.section .sdata

.align 4

/* Generated by spimdisasm 1.42.0 */

nonmatching D_00004958

/* static variable */
dlabel D_00004958
    /* 004958 00004958 00000001 */ .word 0x00000001
    /* 00495C 0000495C 00000000 */ .word 0x00000000
    /* 004960 00004960 00000000 */ .word 0x00000000
    /* 004964 00004964 00000000 */ .word 0x00000000
enddlabel D_00004958
