.include "macro.inc"

.section .sbss

.align 4

/* Generated by spimdisasm 1.42.0 */

.align 2
nonmatching B_STR_00004968, 0x10

/* static variable */
dlabel B_STR_00004968
    /* 00004968 */ .space 0x10

.align 2
nonmatching B_STR_00004978, 0x18

/* static variable */
dlabel B_STR_00004978
    /* 00004978 */ .space 0x18
